name: pretty_barcode
description: Barcode power from package:barcode with pretty QR rendering from package:pretty_qr_code.
version: 0.1.0
homepage: https://github.com/amitsharan/pretty_barcode
repository: https://github.com/amitsharan/pretty_barcode
issue_tracker: https://github.com/amitsharan/pretty_barcode/issues
publish_to: none
topics:
  - barcode
  - qr
  - pretty-qr
  - flutter

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  barcode:
    git: https:///github.com/kumsumit/barcode.git
  flutter:
    sdk: flutter
  pretty_qr_code:
    git: https://github.com/kumsumit/flutter_pretty_qr.git

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.6
